#!/bin/bash
input="msg - [Get]
-PS - 1
-PS - 2
-PS - 3
-PS - 4
-PS - 5
(66 chars long)"

# Process each line
while read -r line; do
  case "$line" in
    "msg - [Get]")
      echo "-PR - 1"
      echo "-PR - 2"
      echo "-PR - 3"
    "-PS - 1"|"-PS - 2"|"-PS - 3")
      echo "dPWR - NP-X"
      
    "-PS - 4"|"-PS - 5")
      echo "dPWR - NP-X"
    *)
      echo "$line"
      ;;
  esac
done <<< "$input"
