#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop
# On the 9th iteration, it also prints "Hi" on a new line

i=1
while [ $i -le 10 ]; do
  echo Best School
  if [ $i -eq 9 ]; then
    echo Hi
  fi
  i=$((i + 1))
done
