#!/usr/bin/env bash
# This script checks the status of a file named 'school'

if [ ! -e school ]; then
  echo "school file doesn't exist"
elif [ -d school ]; then
  echo "school is a directory"
elif [ -f school ]; then
  if [ ! -s school ]; then
    echo "school file exists and is empty"
  else
    echo "school file exists"
  fi
else
  echo "school file doesn't exist"
fi
